/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopapp;

import static desktopapp.MyConnection.getConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author Eugene
 */
public class OrderTable extends javax.swing.JFrame {

    /**
     * Creates new form OrderTable
     */
    public OrderTable() {
        initComponents();
        getConnection();
        showOrderInTable();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public boolean checkInputs() {
        if (descriptionTxt.getText() == null) {
        
        return false;
    }
    else{
    try{
          return true;
    }catch (Exception ex) {
                return false;
            }
}
}


    public ArrayList<Order> getOrderList() {

        ArrayList<Order> orderList = new ArrayList<Order>();
        Connection con = MyConnection.getConnection();
        String query = "Select * From ORDERS";

        Statement st;
        ResultSet rs;
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            Order order;

            while (rs.next()) {
                order = new Order(rs.getLong("id"), rs.getString("description"),
                        rs.getString("orderDate"), rs.getFloat("totalCost"));
                orderList.add(order);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return orderList;
    }

    public void showOrderInTable() {
        ArrayList<Order> list = getOrderList();
        Connection con = MyConnection.getConnection();
        DefaultTableModel model = (DefaultTableModel) tableOrder.getModel();

        model.setRowCount(0);
        Object[] row = new Object[4];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getDescription();
            row[2] = list.get(i).getDate();
            row[3] = list.get(i).getTotalCost();
            model.addRow(row);
        }

        JComboBox combo = new JComboBox<>();
        combo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });

        TableColumn col = tableOrder.getColumnModel().getColumn(3);
        TableCellEditor tce = new DefaultCellEditor(combo);
        col.setCellEditor(tce);
    }

    public void showItem(int index) {
         idTxt.setText(Long.toString(getOrderList().get(index).getId()));
        descriptionTxt.setText(getOrderList().get(index).getDescription());
        orderDateTxt.setText(getOrderList().get(index).getDate());
        totalCostTxt.setText(Float.toString(getOrderList().get(index).getTotalCost()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        q = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        orderDateTxt = new javax.swing.JTextField();
        totalCostTxt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTable = new javax.swing.JMenu();
        menuProductTable = new javax.swing.JMenuItem();
        menuOrderPosition = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description", "Order Date", "Total Cost"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrder);

        jPanel2.setBackground(new java.awt.Color(25, 181, 254));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Description:");

        descriptionTxt.setBackground(new java.awt.Color(218, 223, 225));
        descriptionTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("ID:");

        idTxt.setBackground(new java.awt.Color(218, 223, 225));
        idTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idTxt.setEnabled(false);

        q.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        q.setText("Order Date:");

        a.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        a.setText("Total Cost:");

        orderDateTxt.setEditable(false);
        orderDateTxt.setBackground(new java.awt.Color(218, 223, 225));
        orderDateTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        orderDateTxt.setEnabled(false);

        totalCostTxt.setBackground(new java.awt.Color(218, 223, 225));
        totalCostTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalCostTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(a)
                            .addComponent(q)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(idTxt)
                            .addComponent(totalCostTxt)
                            .addComponent(orderDateTxt))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a))
                        .addGap(43, 43, 43)
                        .addComponent(btnUpdate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        menuTable.setText("Table Selection");
        menuTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTableActionPerformed(evt);
            }
        });

        menuProductTable.setText("Product");
        menuProductTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductTableActionPerformed(evt);
            }
        });
        menuTable.add(menuProductTable);

        menuOrderPosition.setText("Order Position");
        menuOrderPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrderPositionActionPerformed(evt);
            }
        });
        menuTable.add(menuOrderPosition);

        jMenuBar1.add(menuTable);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductTableActionPerformed
        MainWindow mw = new MainWindow();
        mw.setVisible(true);
        mw.pack();
        mw.setLocationRelativeTo(null);
        mw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_menuProductTableActionPerformed

    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        int index = tableOrder.getSelectedRow();
        showItem(index);
    }//GEN-LAST:event_tableOrderMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
   
        if (checkInputs() == true) {

            String updateQuery = null;
            PreparedStatement ps = null;
            Connection con = MyConnection.getConnection();
            try {
                updateQuery = "Update ORDERS SET  description=? where id=?";
                ps = con.prepareStatement(updateQuery);

               
                ps.setString(1, descriptionTxt.getText());
                ps.setLong(2, Long.parseLong(idTxt.getText()));
             
                ps.executeUpdate();
                showOrderInTable();
                JOptionPane.showMessageDialog(null, "Order Update.");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty or wrong.");
        }
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void menuTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTableActionPerformed
 
    }//GEN-LAST:event_menuTableActionPerformed

    private void menuOrderPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrderPositionActionPerformed
     OrderPositionTable op = new OrderPositionTable ();
                    op.setVisible(true);
                    op.pack();
                    op.setLocationRelativeTo(null);
                    op.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
    }//GEN-LAST:event_menuOrderPositionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuOrderPosition;
    private javax.swing.JMenuItem menuProductTable;
    private javax.swing.JMenu menuTable;
    private javax.swing.JTextField orderDateTxt;
    private javax.swing.JLabel q;
    private javax.swing.JTable tableOrder;
    private javax.swing.JTextField totalCostTxt;
    // End of variables declaration//GEN-END:variables
}
